apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-store-csi-driver-secret-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
