apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-store-csi-driver-secret-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: kube-system
roleRef:
  kind: Role
  name: secrets-store-csi-driver-secret-role
  apiGroup: rbac.authorization.k8s.io
