apiVersion: v1
kind: Pod
metadata:
  name: redis-cli
spec:
  containers:
  - name: redis-cli
    image: redis:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
    volumeMounts:
    - name: ca-cert
      mountPath: /etc/ssl/certs/aws-ca.pem
      subPath: ca.pem
  volumes:
  - name: ca-cert
    configMap:
      name: aws-ca-cert
