syncSecret:
  enabled: true

rbac:
  install: true
  
serviceAccount:
  create: true
  name: secrets-store-csi-driver

linux:
  enabled: true
  driver:
    resources: {}

additionalClusterRoleBindings:
  - name: csi-secrets-store-secret-access
    clusterRole:
      name: csi-secrets-store-secret-role
      rules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
    subjects:
      - kind: ServiceAccount
        name: secrets-store-csi-driver
        namespace: kube-system

enableSecretRotation: true
rotationPollInterval: 3600s
