apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "RedisPasswordSecretName"
        objectType: "secretsmanager"
        objectAlias: redis-password
  secretObjects:
  - secretName: aws-secrets
    type: Opaque
    data:
    - objectName: redis-password
      key: redis-password
